app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('listar_tarefas/', listar_tarefas, name='listar_tarefas'),
    path('cadastrar_tarefa/', cadastrar_tarefa, name='cadastrar_tarefa'),
    path('editar_tarefa/<int:id>', editar_tarefa, name='editar_tarefa'),
    path('remover_tarefa/<int:id>', remover_tarefa, name='remover_tarefa'),
]

gerenciador_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ("A", "Alta"),
        ("N", "Normal"),
        ("B", "Baixa")
    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1,choices=PRIORIDADE_CHOICES, null=False)

app/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = '__all__'

app/views.py
from django.shortcuts import render, redirect
from .forms import TarefaForm
from .entidades.tarefa import Tarefa
from .services import tarefa_service


# Create your views here.

def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas()
    return render(request, 'tarefas/listar_tarefas.html',{"tarefas": tarefas})


def cadastrar_tarefa(request):

    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data["titulo"]
            descricao = form_tarefa.cleaned_data["descricao"]
            data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
            prioridade = form_tarefa.cleaned_data["prioridade"]
            tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                                 prioridade=prioridade)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})

def editar_tarefa(request, id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data["titulo"]
        descricao = form_tarefa.cleaned_data["descricao"]
        data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
        prioridade = form_tarefa.cleaned_data["prioridade"]
        tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade)
        tarefa_service.editar_tarefa(tarefa_bd,tarefa_nova)
        return redirect('listar_tarefas')
    return render(request,'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})

def remover_tarefa(request,id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if request.method == "POST":
        tarefa_service.remover_tarefa(tarefa_bd)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Gerenciador de Tarefas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Listar Tarefas</a>
      </li>
    </ul>
  </div>
</nav>
<main class="container" >
    {%block conteudo%}

    {%endblock conteudo%}
</main>

</body>
</html>

app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="card mb-3">
    <div class="card-header">
        Tem certeza que deseja alterar a tarefa abaixo ?
    </div>
    <div class="card-body">
        <h5 class="card-title">{{tarefa.titulo}}</h5>
        <p class="card-text">{{tarefa.descricao}}</p>
        <hr>
        <form method="post">
            {%csrf_token%}
            <button class="btn btn-danger" type="submit">Remover</button>
        </form>
    </div>
</div>

{% endblock conteudo %}

app/templates/tarefas/form_tarefa.html
{%extends 'base.html'%}
{% load meus_filtros %}


{%block conteudo%}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form_tarefa.titulo.errors}}
        <label>Titulo: </label>
        {{form_tarefa.titulo|addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{ form_tarefa.descricao.errors}}
        <label>Descrição: </label>
        {{form_tarefa.descricao|addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{ form_tarefa.data_expiracao.errors}}
        <label>Data de Expiração: </label>
        {{form_tarefa.data_expiracao|addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{ form_tarefa.prioridade.errors}}
        <label>Prioridade: </label>
        {{form_tarefa.prioridade|addclass:'form-control'}}
    </div>

    <div class="form-group">
        <input type="submit" value="Salvar">
    </div>

</form>
{%endblock conteudo%}

app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}

{% block conteudo %}

<h1>Listagem de Tarefas</h1>

{% for tarefa in tarefas %}

<div class="card mb-3">
    <div class="card-header">
        {{tarefa.get_prioridade_display}}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{tarefa.titulo}}</h5>
        <p class="card-text">{{tarefa.descricao}}</p>
        <hr>
        <a href="{% url 'editar_tarefa' tarefa.id%}">Alterar Tarefa</a>
        <a href="{% url 'remover_tarefa' tarefa.id%}">Remover Tarefa</a>

    </div>
</div>

{% endfor %}
<a href="{%url 'cadastrar_tarefa'%}">
<input type="button" class="btn btn-primary mb-3" value="Cadastrar Tarefa">
</a>
{% endblock conteudo %}